# API Settings
api:
  site: ~
  adminUsername: ~
  adminPassword: ~
# ECS Backup & Deletion Settings
ecs:
  saveCountdown: false
  backupScript: ~
  archiveScript: ~
  maxEmptyTime: ~
  backupPeriod: ~
random-tp: ~